UPDATE SERVICE_CONFIGS
SET 
   SERVICE_LABEL = ?
 , SERVICE_ICON = ?
 , SERVICE_IMAGE = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
SERVICE_NAME = ?
;
