SELECT
        STOCK_KNOWLEDGES.*
        ,KNOWLEDGES.TITLE
    FROM
        STOCK_KNOWLEDGES
            LEFT JOIN KNOWLEDGES
                ON STOCK_KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID
    WHERE
        STOCK_KNOWLEDGES.STOCK_ID = ?
        AND KNOWLEDGES.DELETE_FLAG = 0
    ORDER BY
        STOCK_KNOWLEDGES.INSERT_DATETIME DESC LIMIT ? OFFSET ?;
