UPDATE MAIL_HOOK_ADD_KNOWLEDGE_TARGETS
SET 
   TARGET_CLASS = ?
 , TARGET_KIND = ?
 , TARGET_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
CONDITION_NO = ?
 AND HOOK_ID = ?
 AND TARGET_NO = ?
;
