UPDATE MAIL_CONFIGS
SET 
   HOST = ?
 , PORT = ?
 , AUTH_TYPE = ?
 , SMTP_ID = ?
 , SMTP_PASSWORD = ?
 , SALT = ?
 , FROM_ADDRESS = ?
 , FROM_NAME = ?
 , ROW_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
SYSTEM_NAME = ?
;
