UPDATE MAIL_HOOK_CONDITIONS
SET 
   CONDITION_KIND = ?
 , CONDITION = ?
 , PROCESS_USER = ?
 , PROCESS_USER_KIND = ?
 , PUBLIC_FLAG = ?
 , TAGS = ?
 , VIEWERS = ?
 , EDITORS = ?
 , POST_LIMIT = ?
 , LIMIT_PARAM = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
CONDITION_NO = ?
 AND HOOK_ID = ?
;
