UPDATE GROUPS
SET 
   GROUP_KEY = ?
 , GROUP_NAME = ?
 , DESCRIPTION = ?
 , PARENT_GROUP_KEY = ?
 , GROUP_CLASS = ?
 , ROW_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
GROUP_ID = ?
;
