UPDATE USER_ALIAS
SET 
   ALIAS_KEY = ?
 , ALIAS_NAME = ?
 , ALIAS_MAIL = ?
 , USER_INFO_UPDATE = ?
 , ROW_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
AUTH_KEY = ?
 AND USER_ID = ?
;
