ALTER TABLE COMMENTS DROP COLUMN IF EXISTS ANONYMOUS;
ALTER TABLE COMMENTS ADD COLUMN ANONYMOUS integer;
ALTER TABLE KNOWLEDGES DROP COLUMN IF EXISTS ANONYMOUS;
ALTER TABLE KNOWLEDGES ADD COLUMN ANONYMOUS integer;

comment on column COMMENTS.ANONYMOUS is '匿名化';
comment on column KNOWLEDGES.ANONYMOUS is '匿名化';

