UPDATE TEMPLATE_MASTERS
SET 
   TYPE_NAME = ?
 , TYPE_ICON = ?
 , DESCRIPTION = ?
 , INITIAL_VALUE = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
TYPE_ID = ?
;
