SELECT
        USERS.USER_ID, USERS.USER_KEY, USERS.USER_NAME,
        COUNT(KNOWLEDGES.KNOWLEDGE_ID) AS KNOWLEDGE_COUNT,
        COUNT(LIKES.NO) AS LIKE_COUNT,
        COUNT(STOCK_KNOWLEDGES.STOCK_ID) AS STOCK_COUNT
    FROM
        USERS
        LEFT OUTER JOIN KNOWLEDGES ON KNOWLEDGES.INSERT_USER = USERS.USER_ID
        LEFT OUTER JOIN LIKES ON LIKES.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID
        LEFT OUTER JOIN STOCK_KNOWLEDGES ON STOCK_KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID
    WHERE
        USERS.USER_ID = ?
        AND USERS.DELETE_FLAG = 0
        GROUP BY USERS.USER_ID
