SELECT
        USERS.USER_ID
        ,USERS.USER_KEY
        ,USERS.USER_NAME
        ,USERS.PASSWORD
        ,USERS.SALT
        ,USERS.ROW_ID
        ,USERS.INSERT_USER
        ,USERS.INSERT_DATETIME
        ,USERS.UPDATE_USER
        ,USERS.UPDATE_DATETIME
        ,USERS.DELETE_FLAG
        ,USER_GROUPS.GROUP_ROLE
    FROM
        USERS INNER JOIN USER_GROUPS
            ON USERS.USER_ID = USER_GROUPS.USER_ID
WHERE
    USER_GROUPS.GROUP_ID = ?
ORDER BY
    USERS.USER_ID
LIMIT ? OFFSET ?
