SELECT
        COUNT(LIKES.NO) AS LIKE_COUNT
    FROM
        USERS
        INNER JOIN KNOWLEDGES ON (KNOWLEDGES.INSERT_USER = USERS.USER_ID AND KNOWLEDGES.DELETE_FLAG = 0)
        INNER JOIN LIKES ON (LIKES.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID AND LIKES.DELETE_FLAG = 0)
    WHERE
        USERS.USER_ID = ?
        AND USERS.DELETE_FLAG = 0
