SELECT
        USERS.*
        ,USER_GROUPS.GROUP_ROLE
    FROM
        USERS INNER JOIN USER_GROUPS
            ON USERS.USER_ID = USER_GROUPS.USER_ID
WHERE
    USER_GROUPS.GROUP_ID = ?
ORDER BY
    USERS.USER_ID
LIMIT ? OFFSET ?
