SELECT
        USERS.*
        ,USER_GROUPS.GROUP_ROLE
    FROM
        USERS INNER JOIN USER_GROUPS
            ON (USERS.USER_ID = USER_GROUPS.USER_ID
            AND USERS.DELETE_FLAG = 0)
WHERE
    USER_GROUPS.GROUP_ID = ?
ORDER BY
    USERS.USER_ID
LIMIT ? OFFSET ?
