UPDATE HASH_CONFIGS
SET 
   HASH_ITERATIONS = ?
 , HASH_SIZE_BITS = ?
 , ROW_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
SYSTEM_NAME = ?
;
