UPDATE NOTIFICATION_STATUS
SET 
   STATUS = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
TARGET_ID = ?
 AND TYPE = ?
 AND USER_ID = ?
;
