ALTER TABLE KNOWLEDGES ADD COLUMN TAG_IDS character varying(1024);
ALTER TABLE KNOWLEDGES ADD COLUMN TAG_NAMES text;
ALTER TABLE KNOWLEDGES ADD COLUMN LIKE_COUNT bigint;
ALTER TABLE KNOWLEDGES ADD COLUMN COMMENT_COUNT integer;

comment on column KNOWLEDGES.TAG_IDS is 'タグID一覧';
comment on column KNOWLEDGES.TAG_NAMES is 'タグ名称一覧';
comment on column KNOWLEDGES.LIKE_COUNT is 'いいね件数';
comment on column KNOWLEDGES.COMMENT_COUNT is 'コメント件数';
