-- 自動マイグレーションの機能は使わない（v1.12のまま)
ALTER TABLE SURVEY_ITEMS ALTER COLUMN ITEM_NAME TYPE character varying(1024);
ALTER TABLE SURVEY_ITEMS ALTER COLUMN DESCRIPTION TYPE text;
ALTER TABLE TEMPLATE_ITEMS ALTER COLUMN ITEM_NAME TYPE character varying(1024);
ALTER TABLE TEMPLATE_ITEMS ALTER COLUMN DESCRIPTION TYPE text;

