SELECT
		GROUPS.*,
        COUNT(KNOWLEDGE_GROUPS.GROUP_ID) AS GROUP_KNOWLEDGE_COUNT
    FROM
        GROUPS
    LEFT JOIN
    	KNOWLEDGE_GROUPS
    ON
      	GROUPS.GROUP_ID = KNOWLEDGE_GROUPS.GROUP_ID
    WHERE
    	GROUPS.DELETE_FLAG = 0
    GROUP BY
        GROUPS.GROUP_ID
    ORDER BY
    	GROUP_KNOWLEDGE_COUNT DESC
    LIMIT ? OFFSET ?
