UPDATE SURVEY_ITEM_ANSWERS
SET 
   ITEM_VALUE = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
ANSWER_ID = ?
 AND ITEM_NO = ?
 AND KNOWLEDGE_ID = ?
;
