DELETE FROM TEMPLATE_MASTERS WHERE TYPE_ID = -102;
DELETE FROM TEMPLATE_ITEMS WHERE TYPE_ID = -102;

INSERT INTO TEMPLATE_MASTERS ( TYPE_ID, TYPE_NAME, TYPE_ICON, DESCRIPTION, INSERT_USER, INSERT_DATETIME, UPDATE_USER, UPDATE_DATETIME, DELETE_FLAG ) 
VALUES (-102,'presentation', 'fa-television', 'It is presentation by Markdown',0,'2017-12-01 00:00:00',null,null,0);

