UPDATE CONFIRM_MAIL_CHANGES
SET 
   USER_ID = ?
 , MAIL_ADDRESS = ?
 , ROW_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
ID = ?
;
