UPDATE COMMENTS
SET 
   KNOWLEDGE_ID = ?
 , COMMENT = ?
 , COMMENT_STATUS = ?
 , ANONYMOUS = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
COMMENT_NO = ?
;
