UPDATE MAILS
SET 
   STATUS = ?
 , TO_ADDRESS = ?
 , TO_NAME = ?
 , FROM_ADDRESS = ?
 , FROM_NAME = ?
 , TITLE = ?
 , CONTENT = ?
 , ROW_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
MAIL_ID = ?
;
