ALTER TABLE EVENTS DROP COLUMN IF EXISTS TIME_ZONE;
ALTER TABLE EVENTS ADD COLUMN TIME_ZONE character varying(64);
comment on column EVENTS.TIME_ZONE is 'タイムゾーン';

ALTER TABLE EVENTS DROP COLUMN IF EXISTS NOTIFY_STATUS;
ALTER TABLE EVENTS ADD COLUMN NOTIFY_STATUS integer;
comment on column EVENTS.NOTIFY_STATUS is '通知ステータス';

INSERT INTO TEMPLATE_ITEMS ( TYPE_ID, ITEM_NO, ITEM_NAME, ITEM_TYPE, INSERT_USER, INSERT_DATETIME, UPDATE_USER, UPDATE_DATETIME, DELETE_FLAG ) 
VALUES (-101,5,'Place',0,0,'2017-02-16 00:00:00',null,null,0);
