ALTER TABLE EVENTS DROP COLUMN IF EXISTS TIME_ZONE;
ALTER TABLE EVENTS ADD COLUMN TIME_ZONE character varying(64);
comment on column EVENTS.TIME_ZONE is 'タイムゾーン';

ALTER TABLE EVENTS DROP COLUMN IF EXISTS NOTIFY_STATUS;
ALTER TABLE EVENTS ADD COLUMN NOTIFY_STATUS integer;
comment on column EVENTS.NOTIFY_STATUS is '通知ステータス';

