SELECT
        KNOWLEDGES.KNOWLEDGE_ID,
        KNOWLEDGES.TITLE AS KNOWLEDGE_TITLE,
        SURVEYS.TITLE AS TITLE
    FROM
        KNOWLEDGES
        INNER JOIN SURVEYS ON (KNOWLEDGES.KNOWLEDGE_ID = SURVEYS.KNOWLEDGE_ID)
    WHERE
        KNOWLEDGES.DELETE_FLAG = 0
        AND CAST(KNOWLEDGES.KNOWLEDGE_ID AS VARCHAR(20)) LIKE ? || '%'
    ORDER BY
        KNOWLEDGES.KNOWLEDGE_ID ASC 
    LIMIT ? OFFSET ?;
