UPDATE SURVEYS
SET 
   TITLE = ?
 , DESCRIPTION = ?
 , LOGIN_NECESSARY = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
KNOWLEDGE_ID = ?
;
