UPDATE LDAP_CONFIGS
SET 
   DESCRIPTION = ?
 , HOST = ?
 , PORT = ?
 , USE_SSL = ?
 , USE_TLS = ?
 , BIND_DN = ?
 , BIND_PASSWORD = ?
 , SALT = ?
 , BASE_DN = ?
 , FILTER = ?
 , ID_ATTR = ?
 , NAME_ATTR = ?
 , MAIL_ATTR = ?
 , ADMIN_CHECK_FILTER = ?
 , AUTH_TYPE = ?
 , ROW_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
SYSTEM_NAME = ?
;
