SELECT
        NOTICES.*
        ,READ_MARKS.USER_ID AS READED_BY
        ,READ_MARKS.SHOW_NEXT_TIME AS SHOW_NEXT_TIME
    FROM
        NOTICES
            LEFT OUTER JOIN READ_MARKS
                ON (NOTICES.NO = READ_MARKS.NO AND READ_MARKS.USER_ID = ?)
WHERE NOTICES.START_DATETIME < now() AND NOTICES.END_DATETIME > now()
AND NOTICES.DELETE_FLAG = 0
AND (READ_MARKS.USER_ID IS NULL OR READ_MARKS.SHOW_NEXT_TIME = 1);
