UPDATE EVENTS
SET 
   START_DATE_TIME = ?
 , TIME_ZONE = ?
 , NOTIFY_STATUS = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
KNOWLEDGE_ID = ?
;
