SELECT
        KNOWLEDGES.*
        ,USERS.USER_NAME AS INSERT_USER_NAME
        ,UP_USER.USER_NAME AS UPDATE_USER_NAME
        ,EVENTS.START_DATE_TIME AS START_DATE_TIME
    FROM
        KNOWLEDGES
        INNER JOIN EVENTS ON EVENTS.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID
            LEFT OUTER JOIN USERS
                ON USERS.USER_ID = KNOWLEDGES.INSERT_USER
            LEFT OUTER JOIN USERS AS UP_USER
                ON UP_USER.USER_ID = KNOWLEDGES.UPDATE_USER
    WHERE
        EVENTS.START_DATE_TIME >= ?
        AND KNOWLEDGES.DELETE_FLAG = 0
ORDER BY 
        EVENTS.START_DATE_TIME ASC 
LIMIT ? OFFSET ?

