SELECT * FROM STOCK_KNOWLEDGES
    INNER JOIN KNOWLEDGES
        ON KNOWLEDGES.KNOWLEDGE_ID = STOCK_KNOWLEDGES.KNOWLEDGE_ID
 WHERE 
STOCK_KNOWLEDGES.STOCK_ID = ?
 AND STOCK_KNOWLEDGES.DELETE_FLAG = 0
 AND KNOWLEDGES.DELETE_FLAG = 0;
