SELECT
        KNOWLEDGE_HISTORIES.*,
        USERS.USER_NAME
    FROM
        KNOWLEDGE_HISTORIES
        LEFT OUTER JOIN USERS ON (KNOWLEDGE_HISTORIES.UPDATE_USER = USERS.USER_ID)
    WHERE
        KNOWLEDGE_HISTORIES.KNOWLEDGE_ID = ?
        AND KNOWLEDGE_HISTORIES.HISTORY_NO = ?
        AND KNOWLEDGE_HISTORIES.DELETE_FLAG = 0




