UPDATE KNOWLEDGE_HISTORIES
SET 
   TITLE = ?
 , CONTENT = ?
 , PUBLIC_FLAG = ?
 , TAG_IDS = ?
 , TAG_NAMES = ?
 , LIKE_COUNT = ?
 , COMMENT_COUNT = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
HISTORY_NO = ?
 AND KNOWLEDGE_ID = ?
;
