UPDATE USERS
SET 
   USER_KEY = ?
 , USER_NAME = ?
 , PASSWORD = ?
 , SALT = ?
 , LOCALE_KEY = ?
 , MAIL_ADDRESS = ?
 , AUTH_LDAP = ?
 , ROW_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
USER_ID = ?
;
