SELECT NOTIFICATIONS.* , USER_NOTIFICATIONS.STATUS FROM NOTIFICATIONS
INNER JOIN USER_NOTIFICATIONS ON (NOTIFICATIONS.NO = USER_NOTIFICATIONS.NO)
WHERE USER_NOTIFICATIONS.USER_ID = ?
AND USER_NOTIFICATIONS.NO < ?
AND USER_NOTIFICATIONS.DELETE_FLAG = 0
AND NOTIFICATIONS.DELETE_FLAG = 0
ORDER BY USER_NOTIFICATIONS.NO DESC
LIMIT 1 