-- アンケートの項目名＆説明の桁数拡張
ALTER TABLE SURVEY_ITEMS ALTER COLUMN ITEM_NAME TYPE character varying(1024);
ALTER TABLE SURVEY_ITEMS ALTER COLUMN DESCRIPTION TYPE text;
ALTER TABLE TEMPLATE_ITEMS ALTER COLUMN ITEM_NAME TYPE character varying(1024);
ALTER TABLE TEMPLATE_ITEMS ALTER COLUMN DESCRIPTION TYPE text;

-- アンケートはログインしなくても回答できる
ALTER TABLE SURVEYS DROP COLUMN IF EXISTS LOGIN_NECESSARY;
ALTER TABLE SURVEYS ADD COLUMN LOGIN_NECESSARY integer DEFAULT 0;
comment on column SURVEYS.LOGIN_NECESSARY is 'アンケート回答にログインが必須';
