UPDATE WEBHOOK_CONFIGS
SET 
   HOOK = ?
 , URL = ?
 , IGNORE_PROXY = ?
 , TEMPLATE = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
HOOK_ID = ?
;
