SELECT NOTIFICATIONS.* , USER_NOTIFICATIONS.STATUS FROM NOTIFICATIONS
INNER JOIN USER_NOTIFICATIONS ON (NOTIFICATIONS.NO = USER_NOTIFICATIONS.NO)
WHERE USER_NOTIFICATIONS.USER_ID = ?
AND USER_NOTIFICATIONS.STATUS = 0
AND USER_NOTIFICATIONS.DELETE_FLAG = 0
AND NOTIFICATIONS.DELETE_FLAG = 0
ORDER BY NOTIFICATIONS.INSERT_DATETIME DESC
LIMIT ? OFFSET ?
