SELECT
        *
    FROM
        STOCKS INNER JOIN STOCK_KNOWLEDGES
            ON (STOCKS.STOCK_ID = STOCK_KNOWLEDGES.STOCK_ID)
WHERE
    STOCKS.INSERT_USER = ?
    AND STOCKS.DELETE_FLAG = 0
    AND STOCK_KNOWLEDGES.KNOWLEDGE_ID = ?;
