ALTER TABLE KNOWLEDGES DROP COLUMN IF EXISTS VIEW_COUNT;
ALTER TABLE KNOWLEDGES ADD COLUMN VIEW_COUNT bigint;

comment on column KNOWLEDGES.VIEW_COUNT is '参照件数';

create index IDX_VIEW_HISTORIES_INSERT_USER
  on VIEW_HISTORIES(INSERT_USER);

create index IDX_VIEW_HISTORIES_KNOWLEDGE_ID_INSERT_USER
  on VIEW_HISTORIES(KNOWLEDGE_ID,INSERT_USER);

  