ALTER TABLE LOCALES DROP COLUMN IF EXISTS DISP_NAME;
ALTER TABLE LOCALES ADD COLUMN DISP_NAME character varying(128);
comment on column LOCALES.DISP_NAME is '表示名';

ALTER TABLE LOCALES DROP COLUMN IF EXISTS FLAG_ICON;
ALTER TABLE LOCALES ADD COLUMN FLAG_ICON character varying(24);
comment on column LOCALES.FLAG_ICON is '国旗のアイコン';

