UPDATE SURVEY_ITEMS
SET 
   ITEM_NAME = ?
 , ITEM_TYPE = ?
 , DESCRIPTION = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
ITEM_NO = ?
 AND KNOWLEDGE_ID = ?
;
