SELECT 
    USERS.*, PARTICIPANTS.STATUS
FROM
    USERS
    INNER JOIN PARTICIPANTS ON USERS.USER_ID = PARTICIPANTS.USER_ID
WHERE
    PARTICIPANTS.KNOWLEDGE_ID = ?
    AND PARTICIPANTS.DELETE_FLAG = 0
    AND USERS.DELETE_FLAG = 0
 ORDER BY 
    PARTICIPANTS.INSERT_DATETIME
