UPDATE KNOWLEDGE_FILES
SET 
   KNOWLEDGE_ID = ?
 , COMMENT_NO = ?
 , DRAFT_ID = ?
 , FILE_NAME = ?
 , FILE_SIZE = ?
 , FILE_BINARY = ?
 , PARSE_STATUS = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
FILE_NO = ?
;
