UPDATE KNOWLEDGES
SET 
   TITLE = ?
 , CONTENT = ?
 , PUBLIC_FLAG = ?
 , TAG_IDS = ?
 , TAG_NAMES = ?
 , LIKE_COUNT = ?
 , COMMENT_COUNT = ?
 , VIEW_COUNT = ?
 , TYPE_ID = ?
 , NOTIFY_STATUS = ?
 , POINT = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
KNOWLEDGE_ID = ?
;
