SELECT
        KNOWLEDGES.*
        ,COUNT(LIKES.NO) AS LIKE_COUNT_ON_TERM
    FROM
        KNOWLEDGES
            LEFT OUTER JOIN LIKES
                ON (
                    KNOWLEDGES.KNOWLEDGE_ID = LIKES.KNOWLEDGE_ID
                    AND LIKES.INSERT_DATETIME BETWEEN ? AND ?
                )
    WHERE
        KNOWLEDGES.DELETE_FLAG = 0
    GROUP BY
        KNOWLEDGES.KNOWLEDGE_ID
    ORDER BY
        COUNT(LIKES.NO) DESC
        ,KNOWLEDGES.UPDATE_DATETIME DESC 
    LIMIT ? OFFSET ?;
