SELECT
        KNOWLEDGES.*
        ,USERS.USER_NAME AS INSERT_USER_NAME
        ,UP_USER.USER_NAME AS UPDATE_USER_NAME
        ,STOCK_KNOWLEDGE.STOCK_TIME
    FROM
        KNOWLEDGES INNER JOIN (
            SELECT
                    KNOWLEDGES.KNOWLEDGE_ID
                    ,MAX(STOCK_KNOWLEDGES.UPDATE_DATETIME) AS STOCK_TIME
                FROM
                    KNOWLEDGES INNER JOIN STOCK_KNOWLEDGES
                        ON (KNOWLEDGES.KNOWLEDGE_ID = STOCK_KNOWLEDGES.KNOWLEDGE_ID)
            WHERE
                STOCK_KNOWLEDGES.INSERT_USER = ?
                AND STOCK_KNOWLEDGES.STOCK_ID = ?
                AND KNOWLEDGES.DELETE_FLAG = 0
            GROUP BY
                (KNOWLEDGES.KNOWLEDGE_ID)
            ORDER BY
                STOCK_TIME DESC LIMIT ? OFFSET ?
        ) AS STOCK_KNOWLEDGE
            ON KNOWLEDGES.KNOWLEDGE_ID = STOCK_KNOWLEDGE.KNOWLEDGE_ID
        LEFT OUTER JOIN USERS
            ON USERS.USER_ID = KNOWLEDGES.INSERT_USER
        LEFT OUTER JOIN USERS AS UP_USER
            ON UP_USER.USER_ID = KNOWLEDGES.UPDATE_USER
ORDER BY
    STOCK_KNOWLEDGE.STOCK_TIME DESC
