SELECT
        KNOWLEDGES.*
        ,USERS.USER_NAME AS INSERT_USER_NAME
        ,UP_USER.USER_NAME AS UPDATE_USER_NAME
        ,COUNT(LIKES.NO) AS LIKE_COUNT_ON_TERM
    FROM
        KNOWLEDGES
            LEFT OUTER JOIN LIKES
                ON (
                    KNOWLEDGES.KNOWLEDGE_ID = LIKES.KNOWLEDGE_ID
                    AND LIKES.INSERT_DATETIME BETWEEN ? AND ?
                )
            LEFT OUTER JOIN USERS
                ON USERS.USER_ID = KNOWLEDGES.INSERT_USER
            LEFT OUTER JOIN USERS AS UP_USER
                ON UP_USER.USER_ID = KNOWLEDGES.UPDATE_USER
    WHERE
        KNOWLEDGES.DELETE_FLAG = 0
    GROUP BY
        KNOWLEDGES.KNOWLEDGE_ID, USERS.USER_NAME, UP_USER.USER_NAME
    ORDER BY
        COUNT(LIKES.NO) DESC
        ,KNOWLEDGES.UPDATE_DATETIME DESC 
    LIMIT ? OFFSET ?;
