SELECT
        KNOWLEDGES.*
        ,USERS.USER_NAME AS INSERT_USER_NAME
    FROM
        KNOWLEDGES
            LEFT OUTER JOIN USERS
                ON USERS.USER_ID = KNOWLEDGES.INSERT_USER
    WHERE
        KNOWLEDGES.DELETE_FLAG = 0
ORDER BY UPDATE_DATETIME DESC 
LIMIT ? OFFSET ?

