SELECT
        KNOWLEDGES.*
        ,USERS.USER_NAME AS INSERT_USER_NAME
    FROM
        KNOWLEDGES
            LEFT OUTER JOIN USERS
                ON USERS.USER_ID = KNOWLEDGES.INSERT_USER
    WHERE
        KNOWLEDGES.KNOWLEDGE_ID = ?
        AND KNOWLEDGES.DELETE_FLAG = 0;

