SELECT
        TAGS.TAG_ID
        ,TAGS.TAG_NAME
        ,COUNT(KNOWLEDGES.KNOWLEDGE_ID) AS KNOWLEDGE_COUNT
    FROM
        TAGS INNER JOIN KNOWLEDGE_TAGS
            ON TAGS.TAG_ID = KNOWLEDGE_TAGS.TAG_ID INNER JOIN KNOWLEDGES
            ON KNOWLEDGE_TAGS.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID
GROUP BY
    TAGS.TAG_ID
    ,TAGS.TAG_NAME
ORDER BY
    KNOWLEDGE_COUNT DESC LIMIT ? OFFSET ?;