SELECT
        TAGS.TAG_ID
        ,TAGS.TAG_NAME
        ,COUNT(KNOWLEDGES.KNOWLEDGE_ID) AS KNOWLEDGE_COUNT
    FROM
        TAGS 
        INNER JOIN KNOWLEDGE_TAGS
            ON TAGS.TAG_ID = KNOWLEDGE_TAGS.TAG_ID 
        INNER JOIN KNOWLEDGES
            ON KNOWLEDGE_TAGS.KNOWLEDGE_ID = KNOWLEDGES.KNOWLEDGE_ID
    WHERE
        EXISTS (
            SELECT * FROM KNOWLEDGES KNOWLEDGES2 
                INNER JOIN KNOWLEDGE_USERS
                    ON KNOWLEDGES2.KNOWLEDGE_ID = KNOWLEDGE_USERS.KNOWLEDGE_ID
                WHERE
                    KNOWLEDGES.KNOWLEDGE_ID = KNOWLEDGES2.KNOWLEDGE_ID
                AND 
                    KNOWLEDGE_USERS.USER_ID IN (0, ?)
        )
GROUP BY
    TAGS.TAG_ID
    ,TAGS.TAG_NAME
ORDER BY
    KNOWLEDGE_COUNT DESC LIMIT ? OFFSET ?;
    