SELECT
        LIKES.*,
        USERS.USER_NAME
    FROM
        LIKES
        LEFT OUTER JOIN USERS ON (LIKES.INSERT_USER = USERS.USER_ID)
    WHERE
        LIKES.KNOWLEDGE_ID = ?
        AND LIKES.DELETE_FLAG = 0
    ORDER BY
        LIKES.UPDATE_DATETIME DESC LIMIT ? OFFSET ?;




