ALTER TABLE TOKENS DROP COLUMN IF EXISTS TOKEN_TYPE;
ALTER TABLE TOKENS ADD COLUMN TOKEN_TYPE integer default 1 not null;
ALTER TABLE TOKENS DROP COLUMN IF EXISTS ROW_ID;
ALTER TABLE TOKENS ADD COLUMN ROW_ID character varying(64);

DROP INDEX IF EXISTS TOKENS_IX1;

create index TOKENS_IX1
  on TOKENS(USER_ID);

DROP INDEX IF EXISTS TOKENS_IX2;

create index TOKENS_IX2
  on TOKENS(EXPIRES);
