SELECT
        USERS.USER_ID, USERS.USER_KEY, USERS.USER_NAME,
        COUNT(KNOWLEDGES.KNOWLEDGE_ID) AS KNOWLEDGE_COUNT
    FROM
        USERS
        LEFT OUTER JOIN KNOWLEDGES ON (KNOWLEDGES.INSERT_USER = USERS.USER_ID AND KNOWLEDGES.DELETE_FLAG = 0)
    WHERE
        USERS.USER_ID = ?
        AND USERS.DELETE_FLAG = 0
        GROUP BY USERS.USER_ID, USERS.USER_KEY, USERS.USER_NAME
