SELECT USERS.*
FROM USERS
INNER JOIN NOTIFY_CONFIGS ON (USERS.USER_ID = NOTIFY_CONFIGS.USER_ID)
WHERE NOTIFY_CONFIGS.NOTIFY_MAIL = 1
AND NOTIFY_CONFIGS.TO_ITEM_SAVE = 1
AND (NOTIFY_CONFIGS.TO_ITEM_IGNORE_PUBLIC != 1 OR NOTIFY_CONFIGS.TO_ITEM_IGNORE_PUBLIC IS NULL)
AND USERS.DELETE_FLAG != 1
