UPDATE DRAFT_KNOWLEDGES
SET 
   KNOWLEDGE_ID = ?
 , TITLE = ?
 , CONTENT = ?
 , PUBLIC_FLAG = ?
 , ACCESSES = ?
 , EDITORS = ?
 , TAG_NAMES = ?
 , TYPE_ID = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
DRAFT_ID = ?
;
