UPDATE KNOWLEDGE_ITEM_VALUES
SET 
   ITEM_VALUE = ?
 , ITEM_STATUS = ?
 , INSERT_USER = ?
 , INSERT_DATETIME = ?
 , UPDATE_USER = ?
 , UPDATE_DATETIME = ?
 , DELETE_FLAG = ?
WHERE 
ITEM_NO = ?
 AND KNOWLEDGE_ID = ?
 AND TYPE_ID = ?
;
